### ISSUE TITLE
Encoder UI Text

### ISSUE THREAD

**Issue by caievelyn** [rundel/learnrhash#1]
Thank you for this package! It is exactly what I've been looking for in order to record students' interactions with tutorials.

I saw that one of the to-dos for the encoder UI is to allow the text and link to be dynamic. Is there an estimate for when this could be done? I am planning on releasing two tutorials for testing sometime soon, and it would be really helpful if the text could be changed.

**Comment by rundel** [comment]
I've just pushed some changes to the encoder_ui function which will now allow you to pass in a `ui_before` and `ui_after` argument that you can customize using shiny elements and tags. As their name implies the ui elements will be positioned either before or after the hash encoder elements. See https://github.com/rundel/learnrhash/blob/master/inst/demo_iframe.Rmd for an example of using different instructions with an iframe containing the form afterwards.

Let me know if this looks useable to you.

**Comment by caievelyn** [comment]
Yes, just tested it out and it works! Thank you.
