### ISSUE TITLE
The name of the authors is not filled in the DESCRIPTION file

### ISSUE THREAD

**Issue by beatrizmilz** [rundel/learnrhash#13]
Hi Colin! 

I used the `citation()` function to get information to cite `learnrhash` but seems like you need to add the name of the authors in the DESCRIPTION file in order to work correctly.  I'll correct the citation manually in my .bib file, but I think is a good idea to fill the description so is easier for other people to cite the package :) Thanks

```
> citation("learnrhash")

To cite package ‘learnrhash’ in publications use:

  Who wrote it (2021). learnrhash: What the Package Does (Title Case). R package
  version 0.1.0.9000.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {learnrhash: What the Package Does (Title Case)},
    author = {Who wrote it},
    year = {2021},
    note = {R package version 0.1.0.9000},
  }

ATTENTION: This citation information has been auto-generated from the package
DESCRIPTION file and may need manual editing, see ‘help("citation")’.
```

![image](https://user-images.githubusercontent.com/42153618/122641197-147b3980-d0da-11eb-8134-56568cfb8849.png)

**Comment by rundel** [comment]
Complete oversight on my part - the description should be fixed now.
