### ISSUE TITLE
Can't extract questions

### ISSUE THREAD

**Issue by jrpepin** [rundel/learnrhash#16]
I can't decode the hash in RStudio. The decoding logic and ui elements work when deployed in the tutorial. I'm using the developer version of both learnr (learnr_0.10.1.9015) and learnrhash (learnrhash_0.2.0). 

I (students) take the hash and paste it into a .csv file. 
[help.csv](https://github.com/rundel/learnrhash/files/7132807/help.csv)

data <- read.csv("gradebook\\help.csv")
names(data)[names(data) == 'Answer.1'] <- 'hash'
soc294_questions <- extract_questions(data, hash)

But, I get an error like this: 

Error: Assigned data `map(data[[col]], vec_to_wide, col = col, names_sep = names_sep)` must be compatible with existing data.
x Existing data has 2 rows.
x Assigned data has 5 rows.
i Only vectors of size 1 are recycled.

**Comment by rundel** [comment]
The extract functions were super broken as I had forgotten to update them to take into account the changes made with the new learnr state objects. All three should be working now but the output will be slightly different (but hopefully still useful) compared to previous versions.

Let me know if this did not resolve your issue (or created new ones).

**Comment by jrpepin** [comment]
Excellent! The output looks even more helpful than the previous version. Thank you SO MUCH!
