### ISSUE TITLE
Copy-pasting hash with clipr

### ISSUE THREAD

**Issue by caievelyn** [rundel/learnrhash#3]
I was wondering why clipr doesn't seem to work with the current encoding UI, and if you know of any copy-pasting alternatives.
Also, thank you again for your work on this package! We will most certainly be using it in the data science course I'm helping my professor to develop:)

**Comment by rundel** [comment]
clipr was working locally but caused issues when we attempted to use it on shinyapps.io - my plan was to borrow the copy paste feature from the exercises in learn R, this is implemented in javascript and I have not had a chance to wrap my head around how it works.
